- .bumpversion.cfg
- README.md
- setup.py
Makes sheetload be callable from CLI like so: 
```bash
sheetload --sheet_key kshdaksjhdaki281i283 --schema sand --table bb_test_table
```
ran in dev env
Closes #6
> Feature: Make callable

- sheetload/config.py
- sheetload/exceptions.py
- sheetload/flags.py
- sheetload/sheetload.py
- tests/sheets.yml
Brings ability to read the config of a sheet from a yml file. This allows setting column data types correctly for example.
Usage:
From directory where `sheets.yml` file is present:
```bash
sheetload --sheet_name test_sheet
```
Other functionality is preserved (dry run and interactive)
manual tests for expected behaviour
Closes #1  and Fixes #18 
Part of the Jean-Michel Jarre release. To be merged in `dev/jean_michel_jarre`
(At least go through this list mentally or put an `x` between the brackets)
> Feature: Read config from yml file

- sheetload/config.py
- sheetload/sheetload.py
- sheetload/yaml_helpers.py
This fixes the case where sheeloader will always try and find a sheet.yml to validate even if parsing from a key.
> Fix: Move yml validation in config parser

- .github/workflows/pythonapp.yml
- dev-pip-requirements.txt
- pip-requirements.txt
- sheetload/config.py
- sheetload/flags.py
- sheetload/sheetload.py
- sheetload/yaml_helpers.py
- tests/__init__.py
- tests/test_configloader.py
- tests/test_sheetloader.py
This PR does a lot of under the hood action and solves badly written class inheritances by separating classes and passing them as arguments instead.
- It delays parsing of arguments until a proper run and sets default args for testing. Closes #48 
- Data tools requirements are now pinned higher to remove the warnings snowflake connector used to be throwing. Closes #64 
Tests are passing, run against the test sheet and creates the correct output.
> Refactor: Break complex class inheritances, Fix Argparse

- sheetload/config.py
- sheetload/flags.py
- sheetload/sheetload.py
- sheetload/yaml_schema.py
- tests/mockers.py
- tests/sheets.yml
- tests/test_configloader.py
- tests/test_sheetloader.py
Implements feature requested in #50. When providing a column string label of a list of column string labels **exactly** as formatted in the original google sheet, they will be dropped from the data frame obtained from the sheet using `pandas.DataFrame.drop(columns, axis=1)` method.
Unit test for column drop passes.
Closes #50
> Feature: Implement column dropping. Closes #50

- sheetload/config.py
- sheetload/sheetload.py
- sheetload/yaml_schema.py
- tests/sheets.yml
Adds the ability to select a worksheet (aka "tab") inside of a googlesheet by its tab name via the `worksheet:` field in the `sheet.yml` file. 
Tested on an actual sheet as it's hard to mock
Closes #56
> Feature: Add field to parse a worksheet by its name

- sheetload/flags.py
Allows for short argument version for:
- interactive mode: `-i` or `--interactive`
- force: `-f` or `--force`
Tested in cli
Closes #65
> Feature: Make some arguments have a short option

- core/utils.py
Allows passing of CLI arguments as well as parsing from `sheetload_project.yml` for paths of `profiles.yml` and `sheets.yml`.
Fixes a bug that was uncovered withe the `PathFinder().find_nearest_dir_and_file()` which never broke because of misuse of recursive function.
Ran a few test cases passing paths. Bit of a shitty one to write tests for.
Closes #78
> Feature: allow run from anywhere

- pip-requirements.txt
- sheetload/config.py
- tests/mockers.py
- tests/sheets.yml
- tests/test_configloader.py
While columns dict should not be required by design, the implementation in the code make it so. 
Code was refactored to read column dict via `dict.get('key')` instead of `dict['key']`. 
Tested on a real test sheet and added a test case for this as well. All passing.
Closes #88
> Fix: column dict should not be required

- sheetload/sheetload.py
Somehow the prod/dev target schema override was broken when in prod. I belive this happened when I was implementing mypy type hints.
> Fix: Provide a default to SheetBag local copy of target schema

- core/sheetload.py
- pip-requirements.txt
Following the last rounds of refactoring, we do not need to use any of the `data_tools` functionality.
- Imports of `data_tools` modules were removed
- Additional pip requirements were added (they were previously installed by `data_tools`)
- Nasty bug was fixed in the calls to push and check tables in `SheetBag`
All unit tests passing, test against Snowflake and from a real google sheet completed with success.
Closes #99
> Feature: Remove data tools dependency

- .pre-commit-config.yaml
- pip-requirements.txt
CI was failing probably due to one of the pip requirements leaving `snowflake-connector-python` open. 
The internet says pinning to `<2.0.0` might work (https://stackoverflow.com/questions/59982458/importerror-cannot-import-name-py2)
> Fix: snowflake connector issue

- core/main.py
Subcommands in `sheetload upload --help` header were badly displayed due to a bad configuration of the `prog=` argument in argparse.
Closes #77
> Fix: sub command help formatting

- core/sheetload.py
- core/utils.py
- tests/sheets.yml
- tests/test_utils.py
As identified in #145 `core.sheetload.SheetBag.exclude_columns()` would cause `pandas` to raise a `KeyError` if a column up for dropping was not present in the dataframe as no check of any kind was placed in that method 🤦 .
- Implements a generic column in df checker (since this is something other methods should be able to do --refactor will be needed to prefer this newly implemented method over adhoc ones as raised in #149 )
- Calls the new method from `core.utils` to check columns and throw appropriate warnings on `exclude_columns()`.
- unit test `test_check_columns_in_df()` in place and passing on local tests.
- tested on a real sheet and expected behaviour happened.
Closes #145
> Fix: Implement generic col checked and call it in exclude cols

- core/clients/google.py
- core/exceptions.py
- core/utils.py
- tests/test_utils.py
As raised in #123 when duplicate columns are present in the sheet that is about to be imported no warning or test checks. This leads pandas to handle the duplication of the columns by adding a suffix. Since this is mostly hidden it will create confusions in user space if a column was to be submitted for renaming, casting or exclusion.
- duplicate column names in google sheet header will now raise a `DuplicatedColumnsInSheet` error and abort the job.
- tested with a real google sheet
- unit test on dupe checker passing in local tests.
Closes #123
> Feature: Raise error when about to import dupe columns

- README.md
- core/config/config.py
- core/exceptions.py
- core/flags.py
- core/main.py
- core/sheetload.py
- core/yaml/yaml_schema.py
- tests/sheets.yml
- tests/test_configloader.py
- target schema parsing from config and project hierachy was actually broken
- now `flags` has prio, then sheet `Config`, then `Project` if this fails `sheetload` errors
- `dev` mode is deprecated for now as I come up with a better solution to handle this.
- tested with several parameters 
- unitest on the `override_cli_args()` which takes care of comparing the project's default `target_schema` after config was consumed.
Closes #153
> Feature: Handle dev schema fallback in profile

- core/adapters/impl.py
- core/sheetload.py
- `SheetBag` always seems to do too much. One of the things it was doing that it definitely shouldn't was running a query against Snowflake to check that the table had landed.
- `check_table()` was moved to the adaptor as that is where it belongs due to db-specific queries.
Example:
- checked against db
- unitests passing locally
> Refactor: Simplify sheet bag

- core/cleaner.py
- tests/mockers.py
This PR is intended to simplify the cleanup of column names by generating a regular expression based on 2 variables:
- a list of all the characters to replace. By default, only letters will be kept
- the character to replace with. By default `_`
Note that this PR paves the way for introducing custom cleanup parameters. So next step is to parse new configurations
on ipython with a dummy df
- [] I have made corresponding changes to the documentation
> Refactor: simplify columns_cleanups using regexs

- core/flags.py
- core/main.py
- core/task/init.py
Allows to create the credential files for a project which has already being initialised (i.e. project folder and files exist) but for which credential files don't exist yet on a machine
Helps when using a shared codebase
> feat(init_task): :fire: add option to force credentials folder

- core/exceptions.py
- core/task/init.py
`sheetwork init` was creating a "None" project folder when not given a project name.
It now errors earlier to precent a Path called None to be crated
> fix(init_task): :bug: prevent init from creating a None project

- core/adapters/impl.py
- core/utils.py
- pip-requirements.txt
- setup.py
- tests/sheets.yml
- tests/test_utils.py
As explained in #204  and #205 pandas data types are a little too shaky at the minute so we're going to disable casting. This is a regression to pre `1.0.0` behaviour but it worked and at least Snowflake is doing a good job of casting dtypes.
functionality removed, unit tests passing
Closes #205
> fix: :bug: disable df casting, drop `''` cols from dupe check

- core/exceptions.py
- core/flags.py
- core/task/init.py
Throws an error when no command for a task is provided or when a non-implemented task is asked for.
Tests passed, and calling `sheetwork` without a task.
Closes #200
> fix: :lipstick: raise an erro when no command

- .github/workflows/app_ci.yml
- core/adapters/base/connection.py
- core/adapters/base/impl.py
- core/adapters/connection.py
- core/adapters/factory.py
- core/adapters/impl.py
- core/config/config.py
- core/config/profile.py
- core/config/project.py
- core/sheetwork.py
- tests/factory_test.py
- tests/test_profile.py
- Implements ABCs for `BaseSQLAdaptor`, `BaseConnection`, `BaseCredentials`
- Implements `AdaptorContainer` factory which "regusters" and loads concrete adaptors
- `SnowflakeAdaptor` now inherits from `BaseSQLAdaptor`
- `Credentials` is renamed to `BaseCredentials`
- `Connection` is remaled to `BaseConnection`
- `SnowflakeCresdentials` now inherits from `BaseCredentials`
- `SnowflakeConnection` now inherits from `BaseConnection`
- `pip` installer for github actions` now uses the new 2020 resolver to resolve one of the issues had at install.
Tested against a Snowflake instance with expected effects and unit tests are passing.
> feat(adaptor): :factory_worker: Implement Adapter Design

- .github/workflows/app_ci.yml
- sheetwork/core/logger.py
When `--log-level` is set to `debug` the debug level stuff was also printed in the console. But it looked very bad and was hard to separate from the "pretty" print style.
In a way, I made it "uglier" by making the style of the console output in debug mode be really styled like a log message but I find that that's better and more transparent as to what is happening.
I might look into using [Rich](https://github.com/willmcgugan/rich) one of these days to make the experience of the CLI tool a lot better.
But for now it's clearer that way.
> style: :lipstick: make debug console logger be more obvious

- sheetwork/core/adapters/impl.py
- sheetwork/core/exceptions.py
- sheetwork/core/flags.py
- sheetwork/core/main.py
- sheetwork/core/ui/traceback_manager.py
- feat: add flag for long TBs and implement TB manager
- refactor: handle connection error earlier
- fix: string concatenation of SheetWorkError
- tested the error messages pointed to in #209 traceback is either long or not depending on flag provided and errors are coloured as expected
closes #209
> refactor: :lipstick: shorter tracebacks and fix colouring

- sheetwork/core/adapters/impl.py
- sheetwork/core/utils.py
- tests/mockers.py
- tests/test_utils.py
- feat: :bug: add date dtype casting (ignore casting to ints due to known issues with pandas see #204 and #205 
- test: add test for df casting
- updated unit tests
closes #216
> fix: :bug: reintroduce df casting, ignore ints

- .github/workflows/app_ci.yml
- changelog/229.misc.rst
- poetry.lock
- pyproject.toml
- sheetwork/core/clients/google.py
- tests/mockers.py
Google has deprecated `oauth2` in favour of `google_auth`. As a consequence `gspread` provides authentication wrappers which are bound to be more future proof.
`gspread` also takes care of converting `oauth2` -style credentials to the new format which means upgrading to `gspread 3.6` causes **no breaking changa** 
This also allows us to start tackling #227 in order to provide end user-type of authentication.
- chore: :arrow_up: upgrade gspread
- feat(google): :lock: leveage `service_account` wrapper from `gspread` to be more future proof
- chore: update dependencies
Tested **manually** by using my own service account and google sheet. **NOTE:** My service account is actually an old-style `oauth2` account which means I was able to test that the `service_account()` wrapper does what it's …
> refactor: :lock: use `gspread` `service_account` to auth

- .gitignore
- .isort.cfg
- .pre-commit-config.yaml
- README.md
- sheetwork/core/adapters/impl.py
- sheetwork/core/clients/system.py
- sheetwork/core/ui/printer.py
- sheetwork/core/ui/traceback_manager.py
- tests/config_test.py
Was able to ensure that `isort` can sort imports in a similar way to black by reading this article: https://copdips.com/2020/04/making-isort-compatible-with-black.html
> chore: CI add mypy and isort

- changelog/231.feature.rst
- sheetwork/core/clients/google.py
- sheetwork/core/exceptions.py
- sheetwork/core/sheetwork.py
- sheetwork/core/yaml/yaml_schema.py
- tests/google_test.py
- tests/profiles.yml
- tests/sheets.yml
`gspread` has done an amazing work of reworking the google auth to support service account as well as end user authentication.
This PR is an attempt to use `gspread.oauth` to allow for end user authentication.
Currently as mentioned in https://github.com/burnash/gspread/issues/826 `oauth` cannot take a `filename` argument to look for credentials some place else and this currently "contradicts" with the setup of `sheetwork` qua credentials placement. We will have to wait and see if there is a possibility for `gspread.oauth` to take a filename and depending on this we can ship this feature.
Not tested yet, pending some clarity on https://github.com/burnash/gspread/issues/826 to decide how to move forward.
Closes #227
> feat: :lock: allow auth via end user credentials flow

- sheetwork/core/clients/google.py
Makes `GoogleCredentialsFileMissingError` print the actual resolved path for the user credentials when it cannot find it
> fix: :bug: print profile dir path dynamically

- .pre-commit-config.yaml
- sheetwork/core/logger.py
As mentioned in #230 the logger was only printing `DEBUG` level logs to the log file if we had actually asked specifically for `--log-level debug` in the CLI.
This was because the logger was defined with default level `INFO` which meant that it would filter out the message anyway even if the file handler was set up to log anything up from `DEBUG`.
I have now made the global logger level be `DEBUG`, then the console and file handler to the proper filtering of the logs and this means **logger always sends DEBUG info to the file no matter what**
Tested with a test sheet and logs working fine
Pytest seems happy too, so it looks like I didn't break anything
Closes #230
> fix: :bug: set global logger to DEBUG always

- sheetwork/core/adapters/impl.py
- sheetwork/core/config/config.py
As requested in #245 we want to print the database name in the success messages of the table pushes.
This unearthed a few ugly harcoded things which didn't really cause issues but it's good that we caugh it.
Namely the queries in `check_table()` against the info schema have been rewritten to actually populate all db references dynamically.
This should make things a bit nicer and safer for now.
Tested in local dev runs + `pytest` seems all good.
Closes #245
> feat: fully qualify target names

- .pre-commit-config.yaml
- sheetwork/core/adapters/impl.py
- sheetwork/core/config/project.py
- sheetwork/core/task/init.py
- sheetwork/core/yaml/yaml_schema.py
- tests/mockers.py
- tests/project_test.py
- tests/sheetwork_project_all_create.yml
- tests/sheetwork_project_deprecated.yml
- Makes the following profile arguments for object creation available:
- `always_create_table`: when true, tables will be created if they don't exist (and replaced if `destructive_create_table` is `True` --see below)
- `always_create_schema`: when true, schemas will be created (noop yet --this will follow in another PR. At the moment schema and table creation are happening together)
- `always_create_db`: when true a `create database if not exist` will be called (noop yet --this will follow in another PR).
- `destructive_create_table`: when true, if the target table exists already it will be dropped/replaced entirely.
- `always_create_objects`: when true all objects will be created if they do not exist, with the exception of **tables** will not be recreated unless …
> feat: :mage: allow for schema creation

- changelog/262.feature.rst
- sheetwork/core/adapters/impl.py
- sheetwork/core/config/project.py
- sheetwork/core/exceptions.py
- tests/mockers.py
- tests/project_test.py
- tests/sheetwork_project.yml
- tests/sheetwork_project_deprecated.yml
- call `_create_schema` before table creation. This function first checks if a schema exists in the specified database and if it does not it gets created. 
- simplify object_creation_mapping
Tested against Snowflake instance + updated `pytests` for object creation mapping
Closes #260
> feat: :mage: implement schema creation

- changelog/265.feature.rst
- sheetwork/core/adapters/connection.py
- sheetwork/core/config/project.py
- sheetwork/core/flags.py
- sheetwork/core/main.py
- tests/project_test.py
- tests/sheetwork_project.yml
- tests/sheetwork_project_deprecated.yml
In order to override (or set on demand) object creation (tables and schemas) we now provide the following CLI arguments:
- `create-table`
- `create-schema`
- `destructive-create-table`
These arguments are "companions" which can override the following project configuration arguments:
- `always_create_table`
- `always_create_schema`
- `destructive_create_table`
**IMPORTANT**:CLI flags will override whatever is already present in the project config
Tested locally with a bunch of different combination and override + a small `pytest` addition
Closes #264
> feat: allow object creation CLI override

- sheetwork/core/main.py
- sheetwork/core/utils.py
- tests/utils_test.py
When doing `sheetwork --version` we used to be getting the version information twice and the previous simple implementation of `argparse` wasn't able to check PyPI if there was a new release.
Now, the whole version logic lives in a method that always checks PyPI for new version. The function then takes care of generating a string to print directly which can be fed to both `argparse` or called in the `main.py` module.
Tests are updated + tested by doing `sheetwork --version` and `sheetwork upload --dry-run`
Closes #268
> refactor: :lipstick: implement better version checking

- .isort.cfg
- poetry.lock
- pyproject.toml
- sheetwork/core/sheetwork.py
As explained in #275 a flurry of internal/rate limitations have been experienced by end-users.
Instead of patching or extending the `Client` class from `gspread` I wrap `SheetBag._obtain_googlesheet()` with a `@retry` decorator from `retrying`.
`SheetBag._obtain_googlesheet()` will raise only a subset of `gspread.APIErrors` (see codechange). 
We may add to this list as users request it. Or give control over those parameters, but only if this comes up as a painpoint/request.
We might also want to give users the ability to not do retyingings or to customise the number of retries but again this is only if we need to.
Closes #275
> feat: :muscle: add retry decoration to _obtain_googlesheet

- sheetwork/core/config/project.py
- sheetwork/core/utils.py
This PR ensures that deprecation warnings are enabled for the app globally and throws an actual `warning` of category `DeprecationWarning` using the builtin python `warnings` library.
pytest is actually catching the warnings properly which means it's all working fine.
Closes #276
> refactor: handle deprecation warnings more robustly

- .isort.cfg
- poetry.lock
- pyproject.toml
- sheetwork/core/main.py
- sheetwork/core/ui/traceback_manager.py
Uses `pretty-errors` for pretty tracebacks
Closes #284
> refactor: :lipstick: use pretty-errors for tracebacks

- poetry.lock
- pyproject.toml
- sheetwork/core/adapters/impl.py
- sheetwork/core/exceptions.py
- sheetwork/core/utils.py
- tests/mockers.py
- tests/utils_test.py
- add pytest sugar and instafail to dev deps
- implement special handling for bool casting
- Add test for boolean and numeric
Somewhere between `v1.0.0` and up we introduced a bit of a bug/regression with pandas datatype casting prior to database expoure.
When using `df.astype('boolean')` on a string column (which is the way they come to us when read from the google sheet) does not lead to the intended behaviour that string `false` or `true` would get converted to `False` or `True` builtin booleans.
Rather what was happening was that if the string was not null the value that `.astype()` would create is `True` all the time.
Unfortunately boolean conversion was not being covered by the test we had on `cast_pandas_dtypes`. :facepalm:
A hot fix was merged in #289, which consisted in …
> fix: :bug: handle bool casting explicitly

- changelog/295.misc.rst
- sheetwork/core/clients/google.py
- sheetwork/core/exceptions.py
- tests/google_test.py
`make_df_from_worksheet()` was a bit to error hungry and ate all loading errors unless they were of type `WorksheetNotFoundError`. This hid a few errors too many and now that we do retries it was potentially too silent.
Tested manually with a broken sheet.
Was uncovered when trying to replicate #292
> refactor: raise all errors that might happen in loading

- .github/workflows/app_ci.yml
- .github/workflows/tox_suite.yml
- sheetwork/core/exceptions.py
- sheetwork/core/sheetwork.py
- sheetwork/core/utils.py
- tests/mockers.py
- tests/sheetloader_test.py
- tests/utils_test.py
This PR addresses the [issue 293](https://github.com/bastienboutonnet/sheetwork/issues/293). It will raise an error when at least 1 column header is empty.
Locally only with [DIRTY_DF](https://github.com/bastienboutonnet/sheetwork/blob/e0ebbd5ec7a586ecd94af6380c71ca5e378e03d7/tests/mockers.py#L59)
> feat: throw EmptyHeaderError when header contains empty cols

- sheetwork/core/adapters/base/connection.py
- sheetwork/core/adapters/postgres/connection.py
- sheetwork/core/adapters/snowflake/connection.py
- sheetwork/core/config/profile.py
- tests/base_connection_test.py
- tests/mockers.py
- tests/postgres_adaptor_test.py
When we added the Postgres adaptor we made a choice to use `pydantic` to validate the databsde credentials.
Since this simplifies and unifies the code quite a bit this PR ports the same logic into the Snowflake adaptor.
Unit tests should be a good coverage for this
> refactor(adaptors): use pydantic to validate Snowflake creds

- sheetwork/core/config/config.py
- sheetwork/core/main.py
- sheetwork/core/yaml/yaml_helpers.py
- tests/google_test.py
- tests/profile_test.py
- `--version` was broken because of an indentation caveat. This is fixed now
- some rogue prints from testing are also removed. Gosh `1.0.4` was a garbage release!
Closes #310
> fix: make `--version` work again and :broom: some rogue prints

- .github/workflows/app_ci.yml
`pull_request_target` exposes tokens: https://securitylab.github.com/research/github-actions-preventing-pwn-requests and https://www.youtube.com/watch?v=_fpXyS_i1xE
I had turned on this trigger to allow for forks to also be able to publish code coverage to codecov however they now (well for a while) provide tokenless report sending so this should be good.
> ci: change to pull_request trigger to prevent pwn
