bastienboutonnet/sheetwork

.gitignore, sheetload/sheetload.py
Takes care of porting basic load, push functionality reading config from CLI flags
Test run leads to desired output
Closes #2
=> Feature: Basic functionality

sheetload/sheetload.py
Adds:
- string cleaning for column names (spaces, slashes are replaced to underscores and trailing spaces are removed)
- string cleaning for fields (removes trailing spaces)
Example: Ran dbt models on my dev environment with success, implemented `unique` test on `col_A` and dbt test passed.
closes #7
=> Feature: add basic cleanup steps

sheetload/sheetload.py
- Dev runs now set logger level to `debug`
- Dev runs override target schema to `sand`
- `--force` argument forces cli schema argument to be chosen even in "dev" mode.
- adds some table existence checks around column numbers and rows.
tested by manual runs
closes #4
=> Feature: add dev run overrides and more logging

sheetload/sheetload.py
Brings handy `--dry_run` mode via CLI argument. When called:
- db push is skipped
- previews of data frame dtypes are shown
- previews of head of data frame shown
manual test runs 
Closes #3
=> Feature: add dry run previews and skip for pushing

sheetload/flags.py, sheetload/sheetload.py
Brings option to call an interactive choice of whether to perform cleanups or not via a `--i` flag
manual runs
Closes #5
=> Feature: Implement interactive clean up

pip-requirements.txt, setup.py, sheetload/config.py, sheetload/sheetload.py, sheetload/yaml_helpers.py, sheetload/yaml_schema.py, tests/sheets.yml
Adds functions to check that the provided `sheets.yml` contains required fields, that these fields are of the correct type and errors if some unsupported configuration entry is introduced in the yaml file. 
manual tests
closes #19
=> Feature: yml validation

CHANGELOG.md, README.md, sheetload/flags.py
What it does on the tin.
This closes #21, and closes #22
=> Feature: Update changelog, readme, argparse help

setup.py
=> Fix: pass packages kwarg to setup

.bumpversion.cfg
Adds optional step to bumpversion to get correct pre-release behaviour
=> Feature: Add optional step to prerelease

sheetload/flags.py
Fixes issues where prod mode was never true.
=> Fix: mode parsing, and log level settings

README.md
Updates documentation with more information about column naming, formatting and how to find out about formatting with `--dry_run`.
No test required, as code is not touched.
Closes #32
=> Feat: Update documentation on column format.

dev-pip-requirements.txt, sheetload/flags.py, sheetload/sheetload.py, tests/__init__.py, tests/test_cleanups.py
Adds `pytest` testing framework and provides a test for the cleanup step. More will be added later but since this is the section that is most likely to be contributed on it makes sense to have a test on it now.
`pytest` in `sheetload` folder. 
I'm having an issue passing arguments to `pytest` because the `sheetload` argparse thinks the args are for him. Gonna have to look into this but basic testing function works so this is not crucial.
Closes #41
=> Feature: Add testing framework

.github/workflows/pythonapp.yml, google_sheetkey.txt, mypy.ini
This PR sets up configuration for GitHub actions so that `pytest` can be trigged on PR.
There are still quite a few issues to resolve such as access to data_tools for testing. Hoping to solve this with @optroodt soon.
You know...
Closes #44
=> Feature: Test on PR with Actions

.github/workflows/pythonapp.yml
No type hinting is currently implemented in this project so I'm removing those steps from the actions so that we can reduce unecessary checks.
=> Remove mypy to tests since no typehinting yet

.gitignore, sheetload/cleaner.py, sheetload/sheetload.py, tests/test_cleanups.py
Getting cleanup steps out of main class to provide ease in contribution and testing.
Closes #26
=> Feat: Modularise cleanups

.github/workflows/pr_lint.yml
Adding & Testing PR Lint Action
=> Feature: Add pr lint action

.github/workflows/whitespace_linter.yml, sheetload/cleaner.py
Adds a check for trailing whitespace in actions
=> Feature: Add whitespace linter

core/clients/google.py, core/config/config.py, core/config/profile.py, core/config/project.py, core/exceptions.py, core/flags.py, core/main.py, core/utils.py, core/yaml/yaml_helpers.py, core/yaml/yaml_schema.py, tests/mockers.py, tests/profiles.yml, tests/sheetload_project.yml, tests/test_configloader.py, tests/test_profile.py, tests/test_project.py, tests/test_sheetloader.py
Not a lot of changes for the user directly at this point. This is more on how `sheetload` will manage, access and check structure. It does lay some foundations for running `sheetload` from anymore as requested in #78 but this wasn't the primary concern so another PR will follow on this and address this in at least a README.md
Profile read is unit tested, ran also test IRL with a few tests sheets.
Closes #80
=> Feature: Add concept of Project

core/adapters/connection.py, core/adapters/impl.py, core/config/config.py, core/exceptions.py, core/sheetload.py, core/yaml/yaml_schema.py, pip-requirements.txt, tests/mockers.py, tests/sheets.yml, tests/test_configloader.py
- Implements and uses Snowflake adapter functions
- Brings in fix from `dev/daft_punk`
Tested IRL against db as no offline pytest can really be written for Snowflake.
Closes #74 #23 #75
=> Feature: Snowflake Adapter

core/logger.py
- Removes dependency of logger from `data_tools`
- Create a logger which can output logs to a file via handlers (with relative `cwd()` folder creation.
Tested locally and achieves desired output. Needs for unit tests on this are low.
Closes #83
=> Feature: Implement sheetload logger

CONTRIBUTING.md
Writes guidelines for contributing.
=> Doc: Write up contribution guidelines

core/config/profile.py
Removed some rogue prints from testing.
=> Fix: cleanup prints

PULL_REQUEST_TEMPLATE.md, core/clients/google.py, core/config/config.py, core/config/profile.py, core/exceptions.py, core/logger.py, core/sheetload.py, core/ui/colours.py, core/ui/printer.py, core/utils.py, pip-requirements.txt
- Console progress prints are now looking like prints
- Logging to file is always `DEBUG`
- Removed logging of the `profile.yml` which contains passwords and would expose sensitive info.
Closes #101
=> Feature: Fix up printing/logging

codecov.yml, core/sheetload.py
- make some formatting changes and colours
- add confirmation before pushing to database
-called interactive flow and tested
Closes #106
=> Refactor: Improve interactive clean up

codecov.yml, core/sheetload.py
- identified one extra use of column checking and changed it
- manual test to check behaviour and unittests passing locally
Closes #149
=> Refactor: Use new column checker and lower codecov target

CHANGELOG.md
=> Doc: Update changelog

core/sheetload.py
#162 identified a weird flow bug with `--dry_run` where it asked for push to db but aborted after.
This behaviour wasn't intended originally since dry run would just avoid the push but the flow change brings an opportunity to make this a bit more user friendly
- unitests passing locally
- behaviour checked
Closes #162
=> Fix: Allow dry run to ask for conf and override pushing

.github/workflows/app_ci.yml, README.md, dev-pip-requirements.txt
=> Feature: Configure coveralls in github actions

.github/workflows/app_ci.yml, core/clients/system.py, core/exceptions.py, core/flags.py, core/main.py, core/task/init.py
- adds a new task to sheetwork called `init`. This task calls the `tasks.InitTask` instance and tests for folder and files existence.
- depending on existence it creates appropriate files to set up a new project
- when complete, it outputs a nice message that explains to the user what happened, where to find the files they have to change and links to documentation
- no unit tests for this one (I couldn't be bothered)
- tested in local machine and behaviour both with default folders and provided one works out
Example:
- unitest test developed and passing
- executed against db successfully etc.
Closes #168
=> Feature: Setup InitTask

README.md, core/adapters/impl.py, core/flags.py, core/sheetwork.py, core/ui/printer.py
- adds a `timed_message` string formatter/wrapper to add time to certain progress log messages
app runs and unittests pass
Closes #167
=> Feature: Add time in progress logger messages

core/flags.py, core/main.py, core/yaml/yaml_helpers.py
- I was not raising an error which was bad practice.
- Also, removed the `__init__.py` in main level as it was causing issues with the editable installation of the app
=> Fix: Raise NotImplemented, remove init

.github/workflows/app_ci.yml, core/cleaner.py, core/main.py, core/yaml/yaml_schema.py, tests/mockers.py, tests/sheets.yml
As discussed, can't make it pass the yaml validation
=> feat(cleanup): Change yml validator to include custom cleanup

.pre-commit-config.yaml, core/adapters/impl.py, core/clients/google.py, core/config/project.py, core/logger.py, core/task/init.py, core/utils.py, core/yaml/yaml_schema.py
=> feat: :bug: squash minor bugs

.github/workflows/app_ci.yml, .github/workflows/pr_lint.yml, core/main.py
Ars were written with `_` and that's not really best practice. Now they're not and follow POSIX convention
=> chore: :soap: Make CLI args be posix

core/main.py, core/utils.py, dev-pip-requirements.txt, pip-requirements.txt, tests/test_utils.py
Now checks for version againt pypi server
unitests + local runn
=> feat: :rocket: check for updates on launch

.github/workflows/pr_lint.yml, core/config/profile.py
As explained in #199 the error messages from profile parsing weren't very nice.
Now they are!
No tests required
Closes #199
=> style: :lipstick: throw better profile error messages

.gitignore, core/adapters/connection.py, core/adapters/impl.py, core/cleaner.py, core/clients/google.py, core/config/config.py, core/config/profile.py, core/config/project.py, core/exceptions.py, core/flags.py, core/sheetwork.py, core/utils.py, core/yaml/yaml_helpers.py
As a consequence of deciding to use Pylance and to set typing to strict, I've had to consider fixing a bunch of typing issues.
=> chore: :pencil: implement stricter pylance typing guidelines

.pre-commit-config.yaml
Include a summary of the changes this PR is bringing. Bring in any relevant context or motivation for the change that you deem useful to have in this PR description.
Example:
The aim of the PR is achieved by:
- doing this amazing thing
- this other one
- deprecating this thing
- changing this thing
I'd like the reviewer to focus especially on ...
=> chore: :broom: remove exclude python files from mypy precommit

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/app_ci.yml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, _old_changelog.md, tests/sheetwork_project.yml
- chore: :broom: format ymls with prettier
- fix(ci): don't point to a rev
- chore(ci): remove mypy from gh action
=> chore(ci): add prettier pre-commit hook

.github/workflows/pr_lint.yml, poetry.lock, sheetwork/core/adapters/connection.py, sheetwork/core/config/project.py, sheetwork/core/yaml/yaml_schema.py, tests/project_test.py
Include a summary of the changes this PR is bringing. Bring in any relevant context or motivation for the change that you deem useful to have in this PR description.
Example:
The aim of the PR is achieved by:
- doing this amazing thing
- this other one
- deprecating this thing
- changing this thing
I'd like the reviewer to focus especially on ...
=> revert: remove options to create database

.pre-commit-config.yaml, sheetwork/__init__.py, sheetwork/core/adapters/base/connection.py, sheetwork/core/adapters/base/impl.py, sheetwork/core/adapters/connection.py, sheetwork/core/adapters/factory.py, sheetwork/core/cleaner.py, sheetwork/core/clients/google.py, sheetwork/core/clients/system.py, sheetwork/core/config/config.py, sheetwork/core/config/profile.py, sheetwork/core/config/project.py, sheetwork/core/exceptions.py, sheetwork/core/flags.py, sheetwork/core/logger.py, sheetwork/core/main.py, sheetwork/core/sheetwork.py, sheetwork/core/task/init.py, sheetwork/core/ui/colours.py, sheetwork/core/ui/printer.py, sheetwork/core/ui/traceback_manager.py, sheetwork/core/utils.py, sheetwork/core/yaml/yaml_helpers.py, sheetwork/core/yaml/yaml_schema.py
- Adds `flake8` to precommits.
- Cleans up entire `sheetwork/` repo to comply with most of flake8's rules (including docstrings).
No code logic has been changed.
Closes #258
=> chore: :sparkles: make everything flake8 complient

.github/workflows/issue.yml
GitHub action for autolabelling issues
=> chore: add issues.yml

.bumpversion.cfg, CHANGELOG.rst, changelog/CHANGELOG.rst, pyproject.toml, sheetwork/__init__.py, sheetwork/core/_version.py, sheetwork/core/config/project.py, tests/factory_test.py, tests/google_test.py, tests/profile_test.py, tests/project_test.py, tests/sheetloader_test.py
Merge all remaining changes for `1.0.1`
All further changes will now be merged into a new branch for `1.0.2`
=> release: :sparkles: Nicolas Jaar 1.0.1-alpha.1

README.md
Adds a justification of when/why to use sheetwork
Adds some more compatibility information
=> docs: :notebook: update readme with why

pyproject.toml, sheetwork/core/sheetwork.py, sheetwork/core/utils.py, tests/mockers.py, tests/project_test.py, tests/sheetwork_project.yml
HOT FIX: Bool casting doesn't work well. A follow up PR will implement #288 better.
=> fix: regression: turn off boolean casting

.github/workflows/app_ci.yml, .github/workflows/tox_suite.yml, changelog/306.misc.rst, dummy/sheetwork_project.yml, sheetwork/core/clients/system.py, sheetwork/core/config/config.py, sheetwork/core/config/profile.py, sheetwork/core/config/project.py, sheetwork/core/exceptions.py, sheetwork/core/flags.py, sheetwork/core/main.py, sheetwork/core/ui/printer.py, sheetwork/core/utils.py, tests/base_impl_test.py, tests/config_test.py, tests/flags_test.py, tests/google_test.py, tests/init_test.py, tests/main_test.py, tests/printer_test.py, tests/profile_test.py, tests/project_test.py, tests/system_test.py, tests/utils_test.py
- add test for sqlqlchemy dtypes map
- increase tests on system, config, profile, flags
- add more tests on flags
- add tests to main
- Add tests to init task
- Add tests to printer
- Add tests to utils
Also did some quick refactors in the code...
- tests pass
- also kicked a run against a db using a real google sheet and it ran successfully.
Closes #291
=> chore: increase testing coverage

.github/workflows/app_ci.yml, .github/workflows/tox_suite.yml, .gitignore, README.md, dummy/sheetwork_project.yml, tests/init_test.py
Include a summary of the changes this PR is bringing. Bring in any relevant context or motivation for the change that you deem useful to have in this PR description.
Example:
The aim of the PR is achieved by:
- doing this amazing thing
- this other one
- deprecating this thing
- changing this thing
I'd like the reviewer to focus especially on ...
=> ci: modify action for codecov in pr target

.github/workflows/tox_suite.yml, poetry.lock, pyproject.toml
Include a summary of the changes this PR is bringing. Bring in any relevant context or motivation for the change that you deem useful to have in this PR description.
Example:
The aim of the PR is achieved by:
- doing this amazing thing
- this other one
- deprecating this thing
- changing this thing
I'd like the reviewer to focus especially on ...
=> ci: fix tox and tox-poetry-installer compatibility

.github/workflows/pr_lint.yml, poetry.lock, pyproject.toml
- Updates tox and tox-poetry-installer
=> deps: update tox and poetry-tox-installer

sheetwork/core/utils.py, tests/utils_test.py
- add mapping of yes and no to booleans
- update test for handle bools
=> feat: allow for 'yes' and 'no' to map to booleans
